### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by HazimSharif** [Japnime/Google-Drive-Stream-Proxy#18] opened 2018-02-04 18:12 UTC
Hi, Thanks for the code. I tried it on my server, but i get subjected error on chrome

Request URL:http://www.xxx.info/Random/google/stream.php?id=107435f14b7cdbb1&itag=18&source=webdrive&requiressl=yes&mm=30&mn=sn-q4flrnee&ms=nxu&mv=u&pl=24&ttl=transient&ei=EEl3WrqgB4TQqgXEhrnADw&susc=dr&driveid=OWtNSHV5ZzREV0lBNUhWaWUxYWUrMEdLd1VhS29WWVJqMTRoaFFvajhwcz0=&driveapi=japnime&app=explorer&mime=video/mp4&lmt=1408508417332067&mt=1517766606&ip=xxx&token=DmzWt-B-2Bo&domain=aHR0cHM6Ly9yMS0tLXNuLXE0ZmxybmVlLmdvb2dsZXZpZGVvLmNvbS8=&ipbits=0&expire=1517770528&cp=QVNGWUhfT1VQSVhOOkdwY1N1LUYtNVly&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ttl,ei,susc,driveid,app,mime,lmt,cp&signature=130F20A5995DDC744944B82FFF6CE9C4FB42AD1C.0D21FACD020E5250ADF689F7BDD7F3614E6451A8&key=ck2&server=japnimeserver.com
Request Method:GET
Status Code:206 Partial Content
Remote Address:xxx
Referrer Policy:no-referrer-when-downgrade

Response Headers
view source
Accept-Ranges:bytes
CF-RAY:3e7f917196b506e2-LHR
Connection:keep-alive
Content-Length:240156
Content-Range:bytes 0-240155/240156
Content-Type:video/mp4
Date:Sun, 04 Feb 2018 18:07:12 GMT
Server:cloudflare
X-Powered-By:PHP/5.5.36

Request Headers
view source
Accept:*/*
Accept-Encoding:identity;q=1, *;q=0
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Cookie:__cfduid=d4017c70c4d4e88add7e32a542f73a0c41501439273; _ga=GA1.2.1552806601.1502231164
Host:www.xxx.info
Range:bytes=0-
Referer:http://www.xxx.info/Random/google/example.php?id=0B2Vg1UaYogXEclRZTDUxOVdQZFk
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Query String Parameters
view source
view URL encoded
id:107435f14b7cdbb1
itag:18
source:webdrive
requiressl:yes
mm:30
mn:sn-q4flrnee
ms:nxu
mv:u
pl:24
ttl:transient
ei:EEl3WrqgB4TQqgXEhrnADw
susc:dr
driveid:OWtNSHV5ZzREV0lBNUhWaWUxYWUrMEdLd1VhS29WWVJqMTRoaFFvajhwcz0=
driveapi:japnime
app:explorer
mime:video/mp4
lmt:1408508417332067
mt:1517766606
ip:xxx
token:DmzWt-B-2Bo
domain:aHR0cHM6Ly9yMS0tLXNuLXE0ZmxybmVlLmdvb2dsZXZpZGVvLmNvbS8=
ipbits:0
expire:1517770528
cp:QVNGWUhfT1VQSVhOOkdwY1N1LUYtNVly
sparams:ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ttl,ei,susc,driveid,app,mime,lmt,cp
signature:130F20A5995DDC744944B82FFF6CE9C4FB42AD1C.0D21FACD020E5250ADF689F7BDD7F3614E6451A8
key:ck2
server:japnimeserver.com

**Comment by japnimedev** [comment] 2018-02-05 08:38
Duplicate of issue #15

**Comment by japnimedev** [comment] 2018-05-08 16:47
Closed, issue will be added for the new updates.

**Closed as completed by japnimedev** 2018-05-08 16:47 UTC
Labels: on hold
